name: Manual workflow

on:
  workflow_dispatch

env:
  IMAGE: jenkins/jenkins:lts

jobs:
  image-exists:
    runs-on: ubuntu-latest
    steps:
    - name: Check if image exists in Docker Hub
      run: |
        if docker manifest inspect $IMAGE > /dev/null
        then
          echo "Image $IMAGE exists."
          exit 0
        else
          echo "Image $IMAGE doesn't exist."
          exit 1
        fi

  image-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Container image scan
      uses: Azure/container-scan@v0.1
      with:
        image-name: ${{ env.IMAGE }}

  readme-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run mdl
      uses: actionshub/markdownlint@main
      with:
        path: README.md
